version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    configs:
    - source: config
      target: /etc/nginx/conf.d/default.conf
configs:
  config: 
    file: configs/nginx.conf
